# This is a Clojure project that uses boot (not leiningen!)
language: clojure
jdk:
- oraclejdk8
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- export PATH="$PWD:$PATH"
- export BOOT_HOME=.travis.boot
# start xvfb for firefox
before_script:
- phantomjs -v
- firefox -v
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5 # give xvfb some time to start
- boot show --deps
script: boot testc
