# This is a Clojure project that uses boot (not leiningen!)
language: clojure
jdk:
- oraclejdk8
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
- tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
- ln -s phantomjs-2.1.1-linux-x86_64/bin/phantomjs
- export RUNDIR=$(pwd -P)
- export PATH=$RUNDIR:$PATH
- export BOOT_HOME=$RUNDIR/.travis.boot
- export JVM_OPTS="-server -Xms128m -Xmx512m -Xss512k"
- export MAVEN_OPTS=$JVM_OPTS
- export LEIN_JVM_OPTS=$JVM_OPTS
- export BOOT_JVM_OPTIONS=$JVM_OPTS
before_script:
- boot --version
- phantomjs -v
script: boot testc
