# This is a Clojure project that uses boot (not leiningen!)
language: clojure
jdk:
- oraclejdk8
node_js:
 - "4"
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- npm install karma karma-cljs-test karma-cli
- export PATH="$PWD:$PWD/node_modules/.bin;$PATH"
- export BOOT_HOME=.travis.boot
before_script:
- java -version
- boot --version
- phantomjs -v
- karma --version
- firefox -v
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start" # start xvfb for firefox
- sleep 5 # give xvfb some time to start
- boot show --deps
script: boot testc
