language: clojure
jdk:
- oraclejdk8
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- export PATH="$PWD:$PWD/node_modules/karma/bin:$PATH"
- export BOOT_HOME=.travis.boot
- npm install karma
before_script: boot show --deps
script: boot testc
