# This is a Clojure project that uses boot (not leiningen!)
language: clojure
jdk:
- oraclejdk8
# for more extensive browser testing
# node_js:
#  - "4"
install:
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- export PATH="$PWD:$PWD/node_modules/.bin:$PATH"
- export BOOT_HOME=.travis.boot
# for more extensive browser testing
# - npm install karma karma-cljs-test karma-cli
# before_script: boot show --deps
before_script: phantomjs -v
script: boot -v testc
after_script: ls -lR
